[package]
name = "primitives"
version = "0.1.0"
authors = ["Standard Tech"]
edition = "2018"

[dependencies]
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.6", version = "3.0.0", default-features = false }



[features]
default = ["std"]
std = [

	"sp-std/std",

]
