[package]
authors = ['Digital Native Foundation']
build = 'build.rs'
description = 'Opportunity Standalone Testnet'
edition = '2018'
homepage = 'https://standard.tech'
license = 'Unlicense'
name = 'opportunity-standalone'
repository = 'https://github.com/digitalnativeinc/standard-substrate'
version = '3.0.0'

[[bin]]
name = 'opportunity-standalone'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[features]
default = []
runtime-benchmarks = ['opportunity-runtime/runtime-benchmarks']

[build-dependencies]
substrate-build-script-utils = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }

[dependencies]
structopt = "0.3.8"
primitives = { path = "../../primitives", default-features = false }

sc-cli = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6",  features = ["wasmtime"] }
sp-core = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sc-executor = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" , features = ["wasmtime"] }
sc-service = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" , features = ["wasmtime"] }
sc-telemetry = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sc-keystore = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sp-inherents = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sc-transaction-pool = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sp-transaction-pool = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sc-consensus-aura = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sp-consensus-aura = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sp-consensus = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sc-consensus = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sc-finality-grandpa = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sp-finality-grandpa = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sc-client-api = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sp-runtime = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sp-timestamp = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
# These dependencies are used for the node template's RPCs
jsonrpc-core = "15.1.0"
sc-rpc = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sp-api = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sc-rpc-api = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sp-blockchain = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sp-block-builder = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sc-basic-authorship = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
substrate-frame-rpc-system = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
pallet-transaction-payment-rpc = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }

# These dependencies are used for runtime benchmarking
frame-benchmarking = { version = "3.1.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
frame-benchmarking-cli = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }

opportunity-runtime = { path = "../../runtime/opportunity"}
