[package]
authors = ['Digital Native Foundation']
build = 'build.rs'
description = 'Opportunity Node Client.'
edition = '2018'
homepage = 'https://standard.tech'
license = 'Apache-2.0'
name = 'opportunity-standalone'
repository = 'https://github.com/digitalnativeinc/standard-substrate'
version = '2.0.0'

[[bin]]
name = 'opportunity-standalone'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[features]
default = []

[dependencies]
structopt = "0.3.8"
primitives = { path = "../../primitives", default-features = false }
serde_json = { version = "1.0" }
futures = '0.3.4'

sc-cli = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6",  features = ["wasmtime"] }
sp-core = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sc-executor = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" , features = ["wasmtime"] }
sc-service = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" , features = ["wasmtime"] }
sc-telemetry = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sc-keystore = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sp-inherents = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sc-transaction-pool = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sc-consensus-uncles = { version = '0.9.0', git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sc-authority-discovery = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sc-consensus-babe = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sc-consensus-epochs = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sc-consensus-babe-rpc = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sc-network = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sp-consensus-babe = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sp-keystore = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sc-consensus-slots = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sc-chain-spec = { version = '3.0.0', git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sp-authority-discovery = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sp-authorship = { version = '3.0.0', git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sp-consensus = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sc-consensus = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sc-sync-state-rpc = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
grandpa = { version = '0.9.0', package = "sc-finality-grandpa", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
sc-finality-grandpa-rpc = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sp-finality-grandpa = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sc-client-api = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sp-runtime = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sp-timestamp = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
frame-rpc-system = { package="substrate-frame-rpc-system", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
# These dependencies are used for the node template's RPCs
jsonrpc-core = "15.1.0"
sc-rpc = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sp-api = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sc-rpc-api = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sp-blockchain = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sp-block-builder = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
sc-basic-authorship = { version = "0.9.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
pallet-transaction-payment-rpc = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
pallet-im-online = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
pallet-staking = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
pallet-mmr-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }
parity-scale-codec = { version = "2.0.0", default-features = false }
node-primitives = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6" }

# These dependencies are used for runtime benchmarking
frame-benchmarking = { version = "3.1.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
frame-benchmarking-cli = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }

opportunity-runtime = { path = "../../runtime/opportunity"}

[build-dependencies]
substrate-build-script-utils = { version = "3.0.0", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.6"  }
