cargo-features = ["resolver"]

[workspace]
members = [
	"auction",
	"authority",
	"benchmarking",
	"currencies",
	"gradually-update",
	"oracle",
	"oracle/rpc",
	"oracle/rpc/runtime-api",
	"tokens",
	"traits",
	"utilities",
	"vesting",
	"rewards",
	"nft",
	"xtokens",
	"xcm-support",
	"unknown-tokens",
	"build-script-utils",
]
resolver = "2"

[patch.crates-io]
frame-benchmarking = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.6" }
frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.6" }
frame-system = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.6" }
pallet-balances = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.6" }
pallet-elections-phragmen = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.6" }
pallet-scheduler = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.6" }
pallet-treasury = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.6" }
sp-api = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.6" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.6" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.6" }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.6" }
sp-inherents = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.6" }
sp-io = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.6" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.6" }
sp-runtime-interface = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.6" }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.6" }
sp-trie = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.6" }
sp-version = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.6" }
